
defaults:
  - hydra: default
  - model: deflow
  
slurm_id: 00000

wandb_mode: disabled # [offline, disabled, online]
wandb_project_name: seflow

train_data: /home/kin/data/av2/h5py/demo/train
val_data: /home/kin/data/av2/h5py/demo/val
scene_fraction: null

output: ${model.name}-${slurm_id}

checkpoint: 
pretrained_weights: 
eval_only: False

# trainer
num_workers: 8
gpus: 1 # will change in code: torch.cuda.device_count()
sync_bn: true
batch_size: 1
epochs: 3
gradient_clip_val: 5.0

# optimizer ==> Adam
optimizer:
  name: Adam # [Adam, AdamW]
  lr: 2e-4
loss_fn: deflowLoss # choices: [ff3dLoss, zeroflowLoss, deflowLoss, seflowLoss]
# add_seloss: {chamfer_dis: 1.0, static_flow_loss: 1.0, dynamic_chamfer_dis: 1.0, cluster_based_pc0pc1: 1.0}
# ssl_label:

# log settings
seed: 42069
log_every: 10 # steps epochs*dataset_size/batch_size
val_every: 3 # epochs
save_top_model: 5 # top_k model will be saved.

# -----> Model and Task Parameters
voxel_size: [0.2, 0.2, 6]
point_cloud_range: [-51.2, -51.2, -3, 51.2, 51.2, 3]
num_frames: 2

basic_augment: true
beam_dropout:
  enable: false
  p: 0.35
  strategy: half
  drop_ratio_range: [0.25, 0.50]
  min_points: 512

dataset_weight_mode: proportional     # proportional | uniform | designated
dataset_weights: [0.8, 0.1, 0.1]
